# ndarrary介绍
- ndarray：N维数组对象（矩阵），所有元素必须是相同类型。
- ndarray属性：ndim属性，表示维度个数；shape属性，表示各维度大小；dtype属性，表示数据类型。

参考

https://blog.csdn.net/cxmscb/article/details/54583415#t4

https://numpy.org/doc/stable/index.html

https://zhuanlan.zhihu.com/p/478249595

# ndarrary使用

### 创建 ndarrary
- numpyn内部功能函数；
- 从列表等python其他结构转换；
- 使用特殊的库函数。

参考
https://developer.aliyun.com/article/1050654

In [1]:
import numpy as np  
      
a1 = np.array([1,2,3,4],dtype=np.complex128)  
print(a1)  
print("数据类型",type(a1))           #打印数组数据类型  
print("数组元素数据类型：",a1.dtype) #打印数组元素数据类型  
print("数组元素总数：",a1.size)      #打印数组尺寸，即数组元素总数  
print("数组形状：",a1.shape)         #打印数组形状  
print("数组的维度数目",a1.ndim)      #打印数组的维度数目  

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
数据类型 <class 'numpy.ndarray'>
数组元素数据类型： complex128
数组元素总数： 4
数组形状： (4,)
数组的维度数目 1


创建一维/二维数组
1. 内置函数创建常见的矩阵
2. 从python list创建

In [1]:
import numpy as np

array1 = np.arange(20)
array2 = np.arange(20).reshape(4,5)
print(array1)
print(array2)

#创建所有元素为0的数组
a = np.zeros((2,2))
print(1,a,a.shape)
#创建所有元素为1的数组
b = np.ones((3,3))
print(2,b)
##创建所有元素都相同的数组
c = np.full((2,3),6) 
print(3,c)
#创建单位矩阵
d = np.eye(2)
print(4,d)
#创建随机值的矩阵
e = np.random.random((2,2))
print(5,e)
# 从 python list 创建
a = [1,2,3]
b = np.array(a)
c = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a,type(a))
print(b,type(b))
print(c, type(c))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
1 [[0. 0.]
 [0. 0.]] (2, 2)
2 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
3 [[6 6 6]
 [6 6 6]]
4 [[1. 0.]
 [0. 1.]]
5 [[0.76947571 0.75856319]
 [0.59899675 0.76446549]]
[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] <class 'numpy.ndarray'>


### 切片操作
- python中一般包括开始索引，不包括停止索引；
- `-1`表示倒序，为最后一行/列；
- 对于多维数组，每一维度都可指定切片，维度之间用`,`，同一个维度之内用`:`；

##### 一维数组

- `a[i]`返回索引相对应的单个元素；
- `b = a[i:j]`
    - `a[:n]`缺省i，表示0索引元素到n索引元素(不包括n索引)；
    - `a[m:]`缺省j，表示m索引元素到最后一项
    - `a[:]`缺省i,j，表示完整复制a
- `c = a[i:j:s]`s表示步长
    - 当s小于0时，i缺省，默认为-1；j缺省默认为，-len(a)-1

In [17]:
import numpy as np
a = [1,2,3,4,5]
print(1,a[3],len(a))
print(2, a[:4])
print(3, a[2:])
print(4, a[::-1])

1 4 5
2 [1, 2, 3, 4]
3 [3, 4, 5]
4 [5, 4, 3, 2, 1]


#### 二维数组
*技巧*

- 看`,`，如果有逗号，说明对**行**（0维）有操作，需要去看是哪几行；逗号前行操作，逗号后列操作；
- 看`:`，如果有冒号，说明对**列**（1维）有操作，去看操作了哪几列;

In [14]:
import numpy as np
X = np.array([[0,1,2,3],[10,11,12,13],[20,21,22,23],[30,31,32,33]])
#X 是一个二维数组，维度为 0 ，1；第 0 层 [] 表示第 0 维；第 1 层 [] 表示第 1 维；

# X[n0,n1] 表示第 0 维 取第n0 个元素 ，第 1 维取第 n1 个元素
print(1, X[1,0])
# X[1:3,1:3] 表示第 0 维 取 (1:3)元素 ，第 1 维取第(1:3) 个元素
print(2, X[1:3,1:3])

# X[:n0,:n1] 表示第 0 维 取 第0 到 第n0 个元素 ，第 1 维取 第0 到 第n1 个元素
print(3, X[:2,:2])
# X[:,:n1] 表示第 0 维 取 全部元素 ，第 1 维取 第0 到第n1 个元素
print(4, X[:,:2])

# X[:,0]) 表示第 0 维 取全部 元素 ，第 1 维取第 0 个元素
print(5, X[:,0])

1 10
2 [[11 12]
 [21 22]]
3 [[ 0  1]
 [10 11]]
4 [[ 0  1]
 [10 11]
 [20 21]
 [30 31]]
5 [ 0 10 20 30]


## 其他
### np.array()和np.mat()的区别

1. 生成数组所需格式不同
    - mat可以从字符串或列表中生成；
    - array只能从列表中生成

2. 生成的数组计算方式不同
    - array生成数组，用np.dot()表示矩阵乘积，（*）号或np.multiply()表示点乘
    - mat生成数组，（*）和np.dot()相同表示矩阵乘积，点乘只能用np.multiply()

In [16]:
import numpy as np
a = np.mat(data = "1,2;3,4")
b = np.asmatrix([[5,6],[7,8]])
print(a,type(a))
print(b,type(b))

[[1 2]
 [3 4]] <class 'numpy.matrix'>
[[5 6]
 [7 8]] <class 'numpy.matrix'>


In [15]:
import numpy as np
arr_a = np.array([[1,1],[1,1]])
arr_b = np.array([[2,2],[2,2]])
print(np.dot(arr_a,arr_b),type(arr_a),type(arr_b))
print(arr_a*arr_b)
print(np.multiply(arr_a,arr_b))

[[4 4]
 [4 4]] <class 'numpy.ndarray'> <class 'numpy.ndarray'>
[[2 2]
 [2 2]]
[[2 2]
 [2 2]]


In [18]:
import numpy as np
a = np.mat([[1,1],[2,2]])
b = np.mat([[1,1],[2,2]])
print(np.dot(a,b))
print(a*b)
print(np.multiply(a,b))

[[3 3]
 [6 6]]
[[3 3]
 [6 6]]
[[1 1]
 [4 4]]


## numpy中的矩阵运算

In [3]:
#numpy矩阵的点乘
import numpy as np

w = np.array([[0.4], [1.2]])
x = np.array([range(1,6), range(5,10)])

print(w)
print(x)
print(w*x)

[[0.4]
 [1.2]]
[[1 2 3 4 5]
 [5 6 7 8 9]]
[[ 0.4  0.8  1.2  1.6  2. ]
 [ 6.   7.2  8.4  9.6 10.8]]


In [4]:
#numpy矩阵乘
import numpy as np

w = np.array([[0.4, 1.2]])
x = np.array([range(1,6), range(5,10)])

print(w)
print(x)
print(np.dot(w,x))

[[0.4 1.2]]
[[1 2 3 4 5]
 [5 6 7 8 9]]
[[ 6.4  8.   9.6 11.2 12.8]]


## numpy数组编程，加速计算
三个重要概念维Numpy提供强大功能
- 矢量化
- 广播
- 索引

In [19]:
import numpy as np
a =np.eye(2)
print(type(a))

<class 'numpy.ndarray'>


In [22]:
import numpy as np
x = np.array([1, 2, 3])
y = x
z = np.copy(x)
x[0] = 10
print(x,y,z)

[10  2  3] [10  2  3] [1 2 3]


#  无拷贝、深拷贝与浅拷贝

概念

浅拷贝是对另外一个变量的**内存地址**的拷贝，这两个变量指向同一个内存地址。

因此，仅仅拷贝的是内存地址，而不是内存数据。这个变量值为一个地址，它指向了一个内存数据。


### 无拷贝 no copy

简单复制操作，不会产生对象

相当于起个别名，对它进行操作，即本身的操作

In [52]:
import numpy as np
a = np.arange(12)
b = a
b.shape = 3,4 #改变b对象，a对象也会发生改变
print(a, id(a), b, id(b))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2404414234832 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2404414234832


### 浅拷贝 shallow copy or view

- 只copy对象，不copy底层的数据，**共用原始引用**指向的对象数据
- 在view上修改数据，会反映到原始数据
- 切片是特殊的**浅拷贝**

In [55]:
import numpy as np
a = np.arange(12)
b = a
b.shape = 3,4
print(a,id(a))

c = a.view()
c.shape = 2,6
c[1] = 99

print(c,id(c))
print(a,id(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2404414774448
[[ 0  1  2  3  4  5]
 [99 99 99 99 99 99]] 2404414774688
[[ 0  1  2  3]
 [ 4  5 99 99]
 [99 99 99 99]] 2404414774448


## 深拷贝
- 变量的内存地址不同，
- 改变任一变量的值，不相互影响；
- `np.copy()`方法是**深拷贝**；

In [57]:
import numpy as np
a = np.arange(12)
b = a
print(a,id(a))

d = a.copy()
d[1] = 55
print(a, id(a), d, id(d))

[ 0  1  2  3  4  5  6  7  8  9 10 11] 2404414237472
[ 0  1  2  3  4  5  6  7  8  9 10 11] 2404414237472 [ 0 55  2  3  4  5  6  7  8  9 10 11] 2404415818608
